### ISSUE TITLE
Used some of your code

### ISSUE THREAD

**Issue by rjgtorres** [tiasus/HDF5_utils#1]
Hello,

I've used some of your code in the following library: https://github.com/rjgtorres/oo_hdf

Thank you, it really accelerated my project. 

If you wish to use it or steal some parts be my guest! ;)

Best regards,
Ricardo

**Comment by jterwin** [comment]
Ricardo, 

I am happy you liked my code and that it helped you advance your project. I've recently looked into OO Fortran, but I haven't quite figured it out and if it could help my codes (I am also a physicist, studying the atmospheric structure of planets and exoplanets). I will look through your code and it might help me understand Fortran 2003+.

The aim of my project is to hide as many HDF5 types as I can (I still need to keep HID_T for file_id and group_id). My current goals are to better handle error checking, returning on error while closing any open objects, and including an optional, intent(out) hdf_error. Also I am looking into a elegant way to access subsets of the dataset. My current needs are for single column (already implemented) and 2d array along the leading dimensions (next). But hyperslabs could be useful. And there is much more in HDF5, like I see you have chunked datasets, and there is encripted/zipped dataset, all interesting.

Regards,
Justin
